### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by TechplexEngineer**

### CODE REVIEW

**Comment by computergeek1507** [comment]
this repo is mostly a backup to gitbook website, I fixed it in gitbook

**Comment by TechplexEngineer** [comment]
Gotcha. What is the preferred way for contributions?

**Comment by computergeek1507** [comment]
https://app.gitbook.com/invite/-LZ2Jwp43iIiHMV-uNu5/-LZ2Jwp9IIqQn4p2NTcy

**Comment by TechplexEngineer** [comment]
Thanks!

**Pull request closed without merging**
